### ISSUE TITLE
error

### ISSUE THREAD

**Issue by bestofallhans** [born05/craft-assetusage#3] opened 2017-05-03 11:18 UTC
the plugin crashes on multiple asset deletion.

**Comment by roelvanhintum** [comment] 2017-05-03 12:10
Hi @bestofallhans, do you have an error log or a stack trace? It would make debugging a lot faster.

**Comment by roelvanhintum** [comment] 2017-05-05 12:40
@bestofallhans I did some testing, but i couldn't reproduce your issue. Can you provide any information on this?

**Comment by johndwells** [comment] 2017-05-08 11:34
@roelvanhintum I've been looking into this with @bestofallhans, and I do not believe it's an issue with your Asset Usage plugin.  I think you're safe to close this out, we will re-open a new ticket if we learn otherwise!

**Comment by roelvanhintum** [comment] 2017-05-08 11:37
@johndwells thanks for your feedback! Closing now.

**Closed by roelvanhintum** 2017-05-08 11:37 UTC
